### PR TITLE
GH-3713 Add Amulet support

### LINKED ISSUE #3713: [Suggestion] Replace MCEdit with Amulet Map Editor for 1.12.2+
### Role

Sometimes, I incorrectly type a command in a command block and it can get very difficult to delete them.

### Suggestion

MultiMC should substitute the MCEdit editor with Amulet for post 1.12.2 versions.

### Benefit

If you open a world with MCEdit (at least on Windows) and it is post 1.12.2 it is impossible to get anything done with it.

### This suggestion is unique

I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### PR DESCRIPTION
**Pull request by zurgeg**
Needs https://github.com/Amulet-Team/Amulet-Map-Editor/pull/725 to be merged.
Closes GH-3713
TODO:
- [ ] Test
- [x] Finish implementation
- [ ] Fix any known bugs

### CODE REVIEW

**Comment by zurgeg** [comment]
Wait a sec, it just now occured to me that this isn't really needed. oops

**Comment by peterix** [comment]
What do you mean?

Let me at least look at it 🙂

**Comment by zurgeg** [comment]
> What do you mean?
> 
> Let me at least look at it 🙂

I mean that should the above PR get merged, MMC would be able to launch Amulet without any edits, since Amulet and MCEdit would behave the same way in regards to opening worlds from the CLI.

**Comment by allinkdev** [comment]
Thanks! Hope this gets merged! :grin:

**Comment by zurgeg** [comment]
FYI, Implementation should be finished, just need to test.

**Comment by peterix** [comment]
Well, feel free to update this one.

**Comment by zurgeg** [comment]
I'm closing this until someone who's better at C++/C or knows the codebase better can make a PR

**Comment by allinkdev** [comment]
> I'm closing this until someone who's better at C++/C or knows the codebase better can make a PR

Nothing bad appears to catch my eye. I think your code is perfectly apt for achieving this task.

**Comment by peterix** [comment]
Original branch got deleted... But I'm keeping my eye on this :)

**Pull request closed without merging**
