### PR TITLE
add official packages to README

### PR DESCRIPTION
**Pull request by binex-dsk**
This PR adds instructions to install the official Arch Linux and Gentoo Linux packages, as well as some instructions for other distributions and operating systems.

### CODE REVIEW

**Comment by Zetabite** [comment]
multimc-git is not official

**Comment by Zetabite** [comment]
so by default, this pr is already not even in talk to get accepted

**Comment by binex-dsk** [comment]
multimc-git is "official" in the sense that it is the ONLY available, up-to-date package which directly builds and installs this system-wide, not per-user like multimc-bin.

The same thing goes for the ebuild.

**Comment by binex-dsk** [comment]
@peterix Please review, your other maintainers are unaware of the status of the official packages.

**Comment by peterix** [comment]
Begone.

**Pull request closed without merging**
