### PR TITLE
NOISSUE Add Install Legacy Fabric Button

### LINKED ISSUE #4408: An "Install Legacy Fabric" button.
### Role

I would like to play with Legacy Fabric on MultiMC.

### Suggestion

On applicable instances (<=1.13.2) allow the user to select the button, on newer versions, gray it out.

### Benefit

Because it would make playing Legacy Fabric easier. 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Btw their website is here at https://bruh.legacyfabric.net.

I can see this being implemented in multiple ways.

Ungray the Install Fabric button and allow the user to select it, but download legacy fabric instead.

Make a new Install Legacy Fabric button that is grayed on 1.14+

Note: Legacy Fabric doesn't mean older versions of Fabric, it means that it's Fabric for <=1.13.2.

### PR DESCRIPTION
**Pull request by thecatcore**
To merge along side MultiMC/meta#9.
Closes #4408

### CODE REVIEW

**Comment by kb-1000** [comment]
I disagree with how this is done, you're making it confuse Fabric with legacy Fabric.
They're not the same thing, and shouldn't be treated as such.
See https://github.com/MultiMC/Launcher/issues/4408#issuecomment-1006104947

**Comment by arthurbambou** [comment]
Is it really required when basically it installs upstream FabricLoader + Legacy Fabric Intermediary? 🤔

**Comment by PseudoDistant** [comment]
> I disagree with how this is done, you're making it confuse Fabric with Legacy Fabric. They're not the same thing, and shouldn't be treated as such. See [#4408 (comment)](https://github.com/MultiMC/Launcher/issues/4408#issuecomment-1006104947)

> They're not the same thing
Dude they use exactly the same loader, the only thing different is the intermediary file.

**Comment by jamierocks** [comment]
The button reads 'Install Fabric', now I would take that to mean Fabric - not a fork there-of.

This should be implemented as Quilt has just been, not by masquerading a third-party project as the upstream one.

**Comment by PseudoDistant** [comment]
@jamierocks you misunderstand.
It's not a fork, we literally use upstream Fabric Loader.
The only difference is the Intermediary being fed to it.

**Comment by jamierocks** [comment]
I don't misunderstand, I'm well aware of what Legacy Fabric is and isn't - and what Fabric is and isn't.

The button doesn't read 'Install Fabric Loader', it reads 'Install Fabric' - it currently does as I would expect and installs the Fabric Loader, and requires Fabric's intermediaries. These are part of the package that Fabric's installer would install, and together really form part of what most would consider Fabric.

Installing intermediaries from a third-party isn't what I would consider installing Fabric, it would be installing **Legacy Fabric**. Just because the package happens to use Fabric Loader, doesn't make the package what most would understand to be Fabric.

**Comment by arthurbambou** [comment]
Updating accordingly to submitted suggestions.

**Comment by arthurbambou** [comment]
bump

**Comment by arthurbambou** [comment]
oops fixed a typo...

**Comment by JFronny** [comment]
Forgive me if I read this wrong, but wouldn't it make more sense to not disable the button but hide it on newer versions and hide fabric on older ones?
Since neither will ever be available on versions where the other exists and they work as de-facto "equivalents" for another, adding a disabled button seems to me like unneeded clutter and this approach also avoids the problems mentioned by jamierocks.

**Comment by arthurbambou** [comment]
How would I do it?

**Comment by ImperatorStorm** [comment]
Why was this closed?

**Pull request closed without merging**
