### PR TITLE
NOISSUE Patreon button always links to MultiMC

### PR DESCRIPTION
**Pull request by Sebastian-byte**
Another possible solution would be to give an option in CMake build files for a Patreon link.

### CODE REVIEW

**Comment by peterix** [comment]
I did this work on making sure the project can be easily forked, so people would leave me alone...

**Comment by jamierocks** [comment]
I think the better solution here would be to add the CMake option, and keep this as is - holds better to the idea of debranding.

**Comment by peterix** [comment]
No, I am not interested in splintering the branding into multiple locations.

**Comment by peterix** [comment]
If anything, this should be part of the branding, and conditional on the presence of the setting.

**Comment by peterix** [comment]
That is, these should be in `notsecrets` / `secrets`:
image

**Comment by peterix** [comment]
The other option is to actually undo the debranding again... Because the one project that could have done the right thing, didn't. And this whole idea of debranding kind of failed.

**Comment by jamierocks** [comment]
> Because the one project that could have done the right thing, didn't.

I thi

**Comment by peterix** [comment]
Well, parametrizing all of these is consistent at least.

**Comment by peterix** [comment]
But I don't see anything good coming from the debranding after the experience with what came after.

**Comment by peterix** [comment]
On its own, pulling out the magical variables into a common place so they don't have to be kept track of all over the codebase is good.

**Comment by jamierocks** [comment]
> But I don't see anything good coming from the debranding

I think in retrospect, it would have helped if there was an open-source branding variant of the project (like Chromium to Chrome), so that MultiMC was exclusive to multimc.org and 'Multium' could be used by packagers. Launcher is too generic and combined with the logo, screams 'replace me' - which was it's intent, I know.

> On its own, pulling out the magical constants into a common place so they don't have to be kept track of all over the codebase is good.

Agreed :)

**Comment by peterix** [comment]
Anyway, that would be worth a PR

**Pull request closed without merging**
