### PR TITLE
Sandbox MultiMC launcher (again)

### PR DESCRIPTION
**Pull request by cumpootuhr**
Since the first PR (https://github.com/MultiMC/Launcher/pull/4912) was closed prematurely, I never got the chance to address some of the concerns cited as the basis for the first issue's closure. This PR contains additional changes, as requested in the discussion around my first PR.

If additional changes are needed, I would appreciate this time around if I could get the opportunity to address them, instead of the PR simply being closed.

### CODE REVIEW

**Comment by jikuja** [comment]
> If additional changes are needed, I would appreciate this time around if I could get the opportunity to address them, instead of the PR simply being closed.

I'm sure previous PR had enough comments for close reason.

Is there as reason not to do this as custom wrapper command?

**Comment by cumpootuhr** [comment]
> I'm sure previous PR had enough comments for close reason.

The previous PR cited issues with system compatibility and not automatically falling back to un-sandboxed. As both of these issues are trivial to solve, I implemented the solution, but by the time I even saw the issues mentioned, the issue had already been closed. This PR includes the changes I made in response to those comments, and I hope when people have future comments, they can give me a chance to address them before closing the PR.

The discussion in the previous PR also cited that they thought the sandboxing wasn't as strong as they liked or was implemented in the wrong place, which I thought was ridiculous since I've seen no other effort to implement any form of sandboxing. That argument doesn't work unless someone actually implements another option, so I don't see that as a real reason to close a PR until another option is actually presented. Just because it's not perfect doesn't make it useless.

> Is there as reason not to do this as custom wrapper command?

The way my PR is implemented, it's just a modified version of the `run.sh` script that's used to launch MultiMC. It's by far the easiest way to implement sandboxing, since it doesn't require recompilation, and can easily be implemented on a system just by replacing a single shell script after installing the dependency. This model is very basic, and incompatible with per-instance sandboxing (which at least 1 of MultiMC's devs seems to really want), but serves the threat model I intended when implementing sandboxing, and avoids me having to dick around in MultiMC's code trying to get it to integrate with sandboxing, saving me a lot of effort contributing to a project I'm not really that invested in to begin with. So effectively my PR already *is* a custom wrapper command.

I actually had a whole rant written out that I decided not to comment since I still want my PR to get merged. Suffice it to say, I sort of have a bad taste in my mouth from the experience of trying to contribute to this project. Hopefully the devs are open to at the very least collaborating and giving constructive feedback within the range of effort I'm both willing and able to invest into this. I realize it's my change, so I should be at the very least willing to communicate actively with MultiMC's devs to help ensure it doesn't break on people's systems or actively reduce player security. But beyond that, I'm not a MultiMC developer, I'm just a user who wanted MultiMC to exist within a sandbox and figured I'd take the initiative to make that happen.

Anyway, I suggest you read the complete [previous PR](https://github.com/MultiMC/Launcher/pull/4912)'s discussion to understand the context for what I'm saying.

**Comment by theofficialgman** [comment]
> I actually had a whole rant written out that I decided not to comment since I still want my PR to get merged. Suffice it to say, I sort of have a bad taste in my mouth from the experience of trying to contribute to this project. 

Not going to comment again on the content of the PR. Just wanted to note you should have expected this and you time could have been saved if you read the project readme https://github.com/MultiMC/Launcher#development

**Comment by cumpootuhr** [comment]
Ok, this is unrelated to the issue at hand, but... Thanks for pointing me to the readme. If only I had thought to read that. Have you considered maybe I have a reason for not using Discord?

**Comment by Janrupf** [comment]
In any case, this PR will very likely be rejected again. The proper way to sandbox MultiMC would be to have MultiMC control the sandboxing of the game itself - which is something that has been talked about and may be done at some point.

Anyway, talk about development mostly happens on Discord - if you don't feel like chatting on discord that is completely fine and up to you, however, you may run into situations such as this one where you effectively waste time.

Now, something more technical and the "wrapper command thing". MultiMC **already** supports wrapper commands for launching the game, that what is being talked about, not wrapping MultiMC as a whole. You may want to take a look at those, but then again, in order for this to be officially accepted into MultiMC the sandboxing would have to be controlled by MultiMC itself.

**Comment by cumpootuhr** [comment]
I've explained why I think that's unnecessary, and if you're going to shut this down for such a puritan position, I think it's worth pointing out that MultiMC itself isn't devoid of attack surface. As I explained in the previous PR, even if MultiMC controls instance sandboxing, there's no reason MultiMC can't itself be in a less restrictive sandbox. I've mentioned nested sandboxing multiple times.

If doing things a specific way is important enough to reject a PR twice, surely it's important enough for someone other than me to implement. I find it suspect to have so many people shitting on me for how I did things, when exactly nobody has submitted a PR to try to implement it another way.

Perhaps I'd even be willing to write that PR myself, if I actually got the impression the devs were interested in this at all. I'm trying to be receptive to feedback, but right from the start I got people telling me this is useless (an objectively false assertion, as I explained in the old PR), done wrong (I don't see anyone doing it right), and incompatible (an issue I addressed once it was brought up).

I actually thought integrating it into `run.sh` would be something people appreciate. It's less development effort, which is normally appreciated by the developers who have to maintain it once it's tested and merged into a release branch. It's also easier for me, since I don't have to do as much poking around MultiMC's internals. Obviously I was stupid to think that.

Either way, there's simply no reason *not* to merge this (at least, not one that's been cited). Does it break system integration? Maybe, but that's what testing is for. Does it break compatibility? Also maybe, but again, testing. Is it useless? Only if you're biased against this PR and just trying to get it closed. Does it conflict with the long-term intention to have instance sandboxing? Nope. Does it reduce user security? Nope. I've literally gone through every reason cited as why this shouldn't be merged, and explained why they're not sufficient reasons (I've explained this multiple times, in fact).

> Anyway, talk about development mostly happens on Discord - if you don't feel like chatting on discord that is completely fine and up to you, however, you may run into situations such as this one where you effectively waste time.

This would be understandable if there was actually a reason to close this. As I've said, I haven't seen such a reason. But whatever, I'm done arguing at this point, and I'm done justifying myself to y'all. If you have changes you want me to make before merging, lmk. Eventually I might even be the one to implement instance sandboxing, since that *is* a valid suggestion. It just isn't a valid reason to close this PR. This PR doesn't compete with the idea of instance sandboxing. But if you just wanna close this at least give me the courtesy of citing a real reason, otherwise I won't be implementing instance sandboxing, I won't be opening a third PR, and I won't be continuing to use MultiMC.

I realize what I've said might come off as a bit strong, and I hope that doesn't become the reason this PR gets rejected. I'm actively trying to communicate openly and work as a team, within the scope of what I consider reasonable, and I hope this is all just miscommunication. But at least if it gets rejected because y'all don't like me, I'll know the real reason.

**Comment by peterix** [comment]
You want to force this in. That's all I hear. It's not going in, because it breaks launcher functionality, among other things.

**Comment by peterix** [comment]
And I explained multiple reasons why it won't go in i the previous PR, that I closed for those reasons.

You can do this on your own, just by having a wrapper script around MultiMC. And it doesn't have to make other people miserable.

**Comment by cumpootuhr** [comment]
> You want to force this in. That's all I hear. It's not going in, because it breaks launcher functionality, among other things.

Where exactly did I give this impression? Was it the part where I explicitly went out of my way to address the concerns you didn't give me a chance to fix? Or was it where I requested you to give me real reasons instead of bullshit excuses? If expecting you, MultiMC's actual developers, to do your jobs, is making people miserable, then I guess I really was never gonna get this merged. Because even with me writing every line myself, that would still require you to put in the effort to test a contribution to your own project. Of course all you'd hear is me forcing a change, when all you're interested in listening to is reasons not to merge this.

> because it breaks launcher functionality

What exactly do you think testing branches are for? Did I not give you exactly what you asked for when I implemented the fallback logic you specifically asked for? Rinse and repeat. That's how development works, no? But wait, it's not instance-based sandboxing, *right*. As if I haven't already thoroughly explained why that's little more than an excuse underneath a veil of "I would do this better if I were writing this code" style arrogance.

You didn't even give me the chance to fix the issues you brought up. I opened this second PR specifically to address the issues you cited. Not like you actually went into detail about what functionality my issue supposedly broke, because that would require you to do your job and test my change. Because expecting a software developer to so basic debugging is how you create animosity in the community. But rejecting a heavily-requested change on flimsy basis is perfectly fine. As I said, you could at least do me the courtesy of citing the real reason for rejecting this after I went out of my way to appease your concerns while implementing a feature requested by your userbase.

How is "this change might break something" even a real concern? Did I accidentally PR this into a release branch? Is the point of your develop branch not to test changes? Did you not realize testing is a thing you can do before pushing code to release? Seriously, I'm genuinely curious how that can be a reason to reject code where the most complex part is a for loop appending strings based on shell variables.

I know I said I was done arguing, but it's not really arguing once it becomes clear you'll never implement the change. Now it's just telling you off.

**Comment by cumpootuhr** [comment]
I said I won't be using MultiMC. To be entirely clear, that's not because you decided not to merge a PR, it's because you couldn't be bothered to give me reasons that make a lick of sense. I didn't realize it was my job to do the entire development process for you. I didn't realize it would be this hard to merge such a dead-simple change because even telling me what issues a piece of code has so I can fix them, is too much to expect. But I get it, I'm not a MultiMC developer, I'm just a person who thought you'd be open to the idea of implementing a feature that's been requested in about a dozen separate issues over the course of a couple years.

**Comment by peterix** [comment]
I will never implement this change. I was very clear about it in the first PR. If you talked before, you could have learned that and not spent the time on this.

**Comment by peterix** [comment]
And I don't see this being heavily requested. You are the only one as far as I know.

**Comment by peterix** [comment]
Or were ...

**Pull request closed without merging**
