### PR TITLE
Adding the support of jdk 17

### PR DESCRIPTION
**Pull request by CasperOng**
Just basically showed how to solve the issue appeared in https://github.com/MultiMC/Launcher/issues/4319

### CODE REVIEW

**Comment by phit** [comment]
this is already covered in the wiki https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

if you think the wiki needs more info about this you can contribute to that at https://github.com/MultiMC/wiki

**Comment by CasperOng** [comment]
Okay thanks, phit

also, how can I be a contributor?

**Comment by phit** [comment]
Are you talking about the Github tag? I think it's just applied automatically whenever any of your PR's are merged, if you mean actually being a contributor to MultiMC, pick an issue you would like to work on and then come to talk to us on Discord about it if it makes sense to be added. https://discord.gg/multimc

**Comment by CasperOng** [comment]
kk thanks

**Pull request closed without merging**
