### PR TITLE
Display ATLauncher mod warnings and pack messages

### PR DESCRIPTION
**Pull request by jamierocks**
image

### CODE REVIEW

**Comment by cobalt2727** [comment]
```bash
[ 55%] Building CXX object launcher/CMakeFiles/Launcher_logic.dir/modplatform/technic/TechnicPackProcessor.cpp.o
[ 55%] Building CXX object launcher/CMakeFiles/Launcher_logic.dir/modplatform/atlauncher/ATLPackIndex.cpp.o
In file included from /home/cobalt/MultiMC/src/launcher/modplatform/atlauncher/ATLPackIndex.h:19:0,
                 from /home/cobalt/MultiMC/src/launcher/modplatform/atlauncher/ATLPackIndex.cpp:18:
/home/cobalt/MultiMC/src/launcher/modplatform/atlauncher/ATLPackManifest.h:157:28: error: field ‘warnings’ has incomplete type ‘QMap<QString, QString>’
     QMap<QString, QString> warnings;
                            ^~~~~~~~
In file included from /usr/include/aarch64-linux-gnu/qt5/QtCore/qglobal.h:1152:0,
                 from /usr/include/aarch64-linux-gnu/qt5/QtCore/qchar.h:43,
                 from /usr/include/aarch64-linux-gnu/qt5/QtCore/qstring.h:48,
                 from /usr/include/aarch64-linux-gnu/qt5/QtCore/QString:1,
                 from /home/cobalt/MultiMC/src/launcher/modplatform/atlauncher/ATLPackManifest.h:19,
                 from /home/cobalt/MultiMC/src/launcher/modplatform/atlauncher/ATLPackIndex.h:19,
                 from /home/cobalt/MultiMC/src/launcher/modplatform/atlauncher/ATLPackIndex.cpp:18:
/usr/include/aarch64-linux-gnu/qt5/QtCore/qtypeinfo.h:221:1: note: declaration of ‘class QMap<QString, QString>’
 Q_DECLARE_MOVABLE_CONTAINER(QMap);
 ^
[ 55%] Building CXX object launcher/CMakeFiles/Launcher_logic.dir/modplatform/atlauncher/ATLPackInstallTask.cpp.o
[ 55%] Building CXX object launcher/CMakeFiles/Launcher_logic.dir/modplatform/atlauncher/ATLPackManifest.cpp.o
launcher/CMakeFiles/Launcher_logic.dir/build.make:2833: recipe for target 'launcher/CMakeFiles/Launcher_logic.dir/modplatform/atlauncher/ATLPackIndex.cpp.o' failed
make[2]: *** [launcher/CMakeFiles/Launcher_logic.dir/modplatform/atlauncher/ATLPackIndex.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/cobalt/MultiMC/src/launcher/modplatform/atlauncher/ATLPackManifest.cpp:18:0:
/home/cobalt/MultiMC/src/launcher/modplatform/atlauncher/ATLPackManifest.h:157:28: error: field ‘warnings’ has incomplete type ‘QMap<QString, QString>’
     QMap<QString, QString> warnings;
                            ^~~~~~~~
In file included from /usr/include/aarch64-linux-gnu/qt5/QtCore/qglobal.h:1152:0,
                 from /usr/include/aarch64-linux-gnu/qt5/QtCore/qchar.h:43,
                 from /usr/include/aarch64-linux-gnu/qt5/QtCore/qstring.h:48,
                 from /usr/include/aarch64-linux-gnu/qt5/QtCore/QString:1,
                 from /home/cobalt/MultiMC/src/launcher/modplatform/atlauncher/ATLPackManifest.h:19,
                 from /home/cobalt/MultiMC/src/launcher/modplatform/atlauncher/ATLPackManifest.cpp:18:
/usr/include/aarch64-linux-gnu/qt5/QtCore/qtypeinfo.h:221:1: note: declaration of ‘class QMap<QString, QString>’
 Q_DECLARE_MOVABLE_CONTAINER(QMap);
 ^
launcher/CMakeFiles/Launcher_logic.dir/build.make:2861: recipe for target 'launcher/CMakeFiles/Launcher_logic.dir/modplatform/atlauncher/ATLPackManifest.cpp.o' failed
make[2]: *** [launcher/CMakeFiles/Launcher_logic.dir/modplatform/atlauncher/ATLPackManifest.cpp.o] Error 1
CMakeFiles/Makefile2:2025: recipe for target 'launcher/CMakeFiles/Launcher_logic.dir/all' failed
make[1]: *** [launcher/CMakeFiles/Launcher_logic.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by cobalt2727** [comment]
@jamierocks Is there a fix for this in the works?

**Comment by cobalt2727** [comment]
The `aarch64-linux-gnu` in my log can safely be ruled out as irrelevant, for what it's worth:
image

**Comment by jamierocks** [comment]
There is a commit that fixes the build in https://github.com/MultiMC/Launcher/pull/4946 :)

**Comment by cobalt2727** [comment]
Thank you!

**Pull request merged**
