### PR TITLE
GH-4044 Implemented copy screenshots to the clipboard

### PR DESCRIPTION
**Pull request by Ghosty141**
- Added context-menu entry
- Ctrl+C keybind works as well
- If multiple screenshots are selected, only the first one gets copied

One "issue" I noticed, should the switch-case that checks for the pressed key be rewritten to if-else since the check for Ctrl+C cannot be done using the switch?

### CODE REVIEW

**Comment by peterix** [comment]
I'd call this 'copy image data', and only allow it with single selection.

With both multiple selection and single selection, there should be a 'copy' that operates on the file level, not image data level.

**Comment by phit** [comment]
related issue https://github.com/MultiMC/Launcher/issues/4044

**Comment by Ghosty141** [comment]
> I'd call this 'copy image data', and only allow it with single selection.
> 
> With both multiple selection and single selection, there should be a 'copy' that operates on the file level, not image data level.

Implemented in a97d0a3 and e9c52ec . What I noticed, the widebard still contains the item, can this also be changed based on the selection?

**Comment by peterix** [comment]
It should be possible?

Sorry to keep you waiting, but I just got distracted and forgot.

In any case, let's merge this and see what the dev build users think.

**Pull request merged**
